import type { ListingDraft, PhotoChecklist, UploadedImage } from "./types";
import { standardEquipmentCatalog } from "./equipmentCatalog";

export const emptyPhotoChecklist: PhotoChecklist = {
  frontExterior: false,
  rearExterior: false,
  leftSide: false,
  rightSide: false,
  interior: false,
  dashboard: false,
  odometer: false,
  tyres: false,
  serviceBook: false,
  defectsDamage: false,
};

export const completePhotoChecklist: PhotoChecklist = {
  frontExterior: true,
  rearExterior: true,
  leftSide: true,
  rightSide: true,
  interior: true,
  dashboard: true,
  odometer: true,
  tyres: true,
  serviceBook: true,
  defectsDamage: true,
};

export const emptyListingDraft: ListingDraft = {
  id: "custom-draft",
  name: "Custom draft",
  make: "",
  model: "",
  version: "",
  year: 2020,
  productionMonth: "",
  productionYear: 2020,
  firstRegistrationMonth: "",
  firstRegistrationYear: 2020,
  priceChf: 0,
  mileageKm: 0,
  fuelType: "",
  transmission: "",
  bodyType: "",
  sellerType: "private",
  mfkStatus: "unknown",
  serviceHistoryStatus: "unknown",
  accidentHistoryStatus: "unknown",
  warrantyStatus: "unknown",
  exteriorColor: "",
  interiorColor: "",
  metallic: false,
  description: "",
  photoCount: 0,
  uploadedImages: [],
  photoChecklist: emptyPhotoChecklist,
  keyFeatures: [],
  standardEquipment: [],
  optionalEquipment: [],
  retrofits: [],
  technicalData: {},
  batteryData: {},
  sellerNotes: "",
};

export const demoListings: ListingDraft[] = [
  {
    id: "demo-bmw-320d-weak",
    name: "Guided demo: BMW 320d needs trust proof",
    make: "BMW",
    model: "320d Touring",
    version: "xDrive Steptronic",
    year: 2016,
    productionMonth: "April",
    productionYear: 2016,
    firstRegistrationMonth: "April",
    firstRegistrationYear: 2016,
    priceChf: 13800,
    mileageKm: 174000,
    fuelType: "Diesel",
    transmission: "Automatic",
    bodyType: "Estate",
    sellerType: "private",
    mfkStatus: "unknown",
    serviceHistoryStatus: "partial",
    accidentHistoryStatus: "unknown",
    warrantyStatus: "none",
    exteriorColor: "Grey",
    interiorColor: "Black",
    metallic: true,
    description:
      "BMW 320d Touring in good condition. Drives well and has lots of space. Selling because I bought another car. Call for more info.",
    photoCount: 6,
    uploadedImages: addExtraImages([
      { id: "bmw-front", name: "bmw-front.jpg", coverage: "frontExterior" },
      { id: "bmw-rear", name: "bmw-rear.jpg", coverage: "rearExterior" },
      { id: "bmw-side", name: "bmw-left-side.jpg", coverage: "leftSide" },
      { id: "bmw-interior", name: "bmw-interior.jpg", coverage: "interior" },
    ], 6, "bmw-detail"),
    photoChecklist: {
      ...emptyPhotoChecklist,
      frontExterior: true,
      rearExterior: true,
      leftSide: true,
      interior: true,
    },
    keyFeatures: ["Automatic", "Navigation"],
    standardEquipment: pickItems(standardEquipmentCatalog, 24, 2),
    optionalEquipment: ["Navigation system", "Metallic paint"],
    retrofits: [],
    technicalData: {
      doors: 5,
      seats: 5,
      powerHp: 190,
      powerKw: 140,
      emptyWeightKg: 1695,
      towingCapacityBrakedKg: 1800,
      lengthMm: 4633,
      widthMm: 1811,
      heightMm: 1429,
      energyLabel: "D",
    },
    sellerNotes: "Summer tyres mounted, winter wheels may be available.",
  },
  {
    id: "demo-toyota-rav4-strong",
    name: "Strong Toyota RAV4 Hybrid",
    make: "Toyota",
    model: "RAV4 Hybrid",
    version: "Premium AWD",
    year: 2020,
    productionMonth: "June",
    productionYear: 2020,
    firstRegistrationMonth: "June",
    firstRegistrationYear: 2020,
    priceChf: 31900,
    mileageKm: 68000,
    fuelType: "Hybrid",
    transmission: "Automatic",
    bodyType: "SUV",
    sellerType: "dealer",
    mfkStatus: "valid",
    serviceHistoryStatus: "complete",
    accidentHistoryStatus: "accident-free",
    warrantyStatus: "dealer warranty",
    exteriorColor: "Blue",
    interiorColor: "Black",
    metallic: true,
    description:
      "Well maintained Swiss Toyota RAV4 Hybrid with complete Toyota service history, fresh MFK, accident-free bodywork, two keys, winter wheels, adaptive cruise control, navigation, reversing camera, and documented hybrid system checks.",
    photoCount: 18,
    uploadedImages: addExtraImages([
      { id: "rav-front", name: "rav4-front.jpg", coverage: "frontExterior" },
      { id: "rav-rear", name: "rav4-rear.jpg", coverage: "rearExterior" },
      { id: "rav-left", name: "rav4-left.jpg", coverage: "leftSide" },
      { id: "rav-right", name: "rav4-right.jpg", coverage: "rightSide" },
      { id: "rav-interior", name: "rav4-interior.jpg", coverage: "interior" },
      { id: "rav-dashboard", name: "rav4-dashboard.jpg", coverage: "dashboard" },
      { id: "rav-odometer", name: "rav4-odometer.jpg", coverage: "odometer" },
      { id: "rav-tyres", name: "rav4-tyres.jpg", coverage: "tyres" },
      { id: "rav-service", name: "rav4-service-book.jpg", coverage: "serviceBook" },
      { id: "rav-defects", name: "rav4-defects-none.jpg", coverage: "defectsDamage" },
    ], 18, "rav4-detail"),
    photoChecklist: completePhotoChecklist,
    keyFeatures: [
      "Adaptive cruise control",
      "Navigation",
      "Rear camera",
      "Winter wheels",
      "Hybrid system check",
      "Two keys",
    ],
    standardEquipment: pickItems(standardEquipmentCatalog, 42, 5),
    optionalEquipment: ["Winter wheels", "Premium audio system", "Technology package"],
    retrofits: ["Swiss motorway vignette holder"],
    technicalData: {
      doors: 5,
      seats: 5,
      powerHp: 222,
      powerKw: 163,
      emptyWeightKg: 1745,
      towingCapacityBrakedKg: 1650,
      lengthMm: 4600,
      widthMm: 1855,
      heightMm: 1685,
      typeApprovalNumber: "1TA512",
      vehicleIdentificationNumber: "JTMGBREV80D123456",
      energyLabel: "B",
    },
    sellerNotes: "Includes dealer warranty and fresh detailing before handover.",
  },
  {
    id: "demo-vw-golf-risky",
    name: "Risky VW Golf",
    make: "Volkswagen",
    model: "Golf 1.4 TSI",
    version: "Comfortline",
    year: 2013,
    productionMonth: "January",
    productionYear: 2013,
    firstRegistrationMonth: "January",
    firstRegistrationYear: 2013,
    priceChf: 3900,
    mileageKm: 186000,
    fuelType: "Petrol",
    transmission: "Manual",
    bodyType: "Hatchback",
    sellerType: "private",
    mfkStatus: "missing",
    serviceHistoryStatus: "unknown",
    accidentHistoryStatus: "unknown",
    warrantyStatus: "none",
    exteriorColor: "Black",
    interiorColor: "",
    metallic: false,
    description: "Good car. Must sell quickly. Call me.",
    photoCount: 4,
    uploadedImages: [
      { id: "golf-front", name: "golf-front.jpg", coverage: "frontExterior" },
      { id: "golf-rear", name: "golf-rear.jpg", coverage: "rearExterior" },
      { id: "golf-left", name: "golf-left.jpg", coverage: "leftSide" },
      { id: "golf-right", name: "golf-right.jpg", coverage: "rightSide" },
    ],
    photoChecklist: {
      ...emptyPhotoChecklist,
      frontExterior: true,
      rearExterior: true,
      leftSide: true,
      rightSide: true,
    },
    keyFeatures: [],
    standardEquipment: pickItems(standardEquipmentCatalog, 10, 8),
    optionalEquipment: [],
    retrofits: [],
    technicalData: {
      doors: 5,
      seats: 5,
      powerHp: 122,
      powerKw: 90,
      emptyWeightKg: 1280,
      energyLabel: "E",
    },
    sellerNotes: "Cheap because I need space.",
  },
  {
    id: "demo-tesla-model-y-premium",
    name: "Premium Tesla Model Y",
    make: "Tesla",
    model: "Model Y",
    version: "Long Range AWD",
    year: 2023,
    productionMonth: "March",
    productionYear: 2023,
    firstRegistrationMonth: "March",
    firstRegistrationYear: 2023,
    priceChf: 55900,
    mileageKm: 37000,
    fuelType: "Electric",
    transmission: "Automatic",
    bodyType: "SUV",
    sellerType: "dealer",
    mfkStatus: "valid",
    serviceHistoryStatus: "complete",
    accidentHistoryStatus: "accident-free",
    warrantyStatus: "battery warranty",
    exteriorColor: "Pearl White",
    interiorColor: "Black",
    metallic: false,
    description:
      "Tesla Model Y Long Range AWD from Swiss first registration with valid MFK, accident-free history, remaining battery warranty, clean interior, summer and winter wheels, Type 2 charging cable, enhanced Autopilot package, panoramic glass roof, and 360-degree photo documentation.",
    photoCount: 22,
    uploadedImages: addExtraImages([
      { id: "tesla-front", name: "model-y-front.jpg", coverage: "frontExterior" },
      { id: "tesla-rear", name: "model-y-rear.jpg", coverage: "rearExterior" },
      { id: "tesla-left", name: "model-y-left.jpg", coverage: "leftSide" },
      { id: "tesla-right", name: "model-y-right.jpg", coverage: "rightSide" },
      { id: "tesla-interior", name: "model-y-interior.jpg", coverage: "interior" },
      { id: "tesla-dashboard", name: "model-y-dashboard.jpg", coverage: "dashboard" },
      { id: "tesla-odometer", name: "model-y-odometer.jpg", coverage: "odometer" },
      { id: "tesla-tyres", name: "model-y-tyres.jpg", coverage: "tyres" },
      { id: "tesla-service", name: "model-y-warranty.jpg", coverage: "serviceBook" },
      { id: "tesla-defects", name: "model-y-defects-none.jpg", coverage: "defectsDamage" },
    ], 22, "model-y-detail"),
    photoChecklist: completePhotoChecklist,
    keyFeatures: [
      "Long Range AWD",
      "Battery warranty",
      "Type 2 charging cable",
      "Enhanced Autopilot",
      "Panoramic glass roof",
      "Winter wheels",
    ],
    standardEquipment: pickItems(standardEquipmentCatalog, 48, 0),
    optionalEquipment: ["Enhanced Autopilot", "Tow hitch preparation", "Winter package"],
    retrofits: ["Ceramic paint protection"],
    technicalData: {
      doors: 5,
      seats: 5,
      powerHp: 514,
      powerKw: 378,
      emptyWeightKg: 2048,
      towingCapacityBrakedKg: 1600,
      lengthMm: 4751,
      widthMm: 1921,
      heightMm: 1624,
      typeApprovalNumber: "1TE123",
      vehicleIdentificationNumber: "LRWYGCEE0PC123456",
      serialNumber: "AS24-TESLA-001",
      vehicleNumber: "ZH-2023-5544",
      energyLabel: "A",
    },
    batteryData: {
      rangeKm: 533,
      batteryCapacityKWh: 75,
      batteryOwnershipModel: "Included in purchase price",
      batteryHealthPercent: 94,
      hasBatteryHealthCertificate: true,
      chargingPlugAc: "Type 2",
      chargingPowerAcKw: 11,
      chargingTimeAcMinutes: 420,
      chargingPlugDc: "CCS",
      chargingPowerDcKw: 250,
      chargingTimeDcMinutes: 28,
      chargingCableIncluded: true,
    },
    sellerNotes: "Premium price reflects warranty, documentation, and complete photo set.",
  },
];

function pickItems(items: string[], count: number, offset: number) {
  return Array.from({ length: count }, (_, index) => items[(index + offset) % items.length]).filter(
    Boolean,
  );
}

function addExtraImages(images: UploadedImage[], targetCount: number, prefix: string) {
  return [
    ...images,
    ...Array.from({ length: Math.max(0, targetCount - images.length) }, (_, index) => ({
      id: `${prefix}-${index + 1}`,
      name: `${prefix}-${index + 1}.jpg`,
      coverage: "other" as const,
    })),
  ];
}
