export const standardEquipmentCatalog = [
  "12-volt socket",
  "ABS and brake assist",
  "Adaptive cruise control",
  "Air conditioning",
  "Airbag driver and passenger",
  "Airbag front and rear side",
  "Alarm system",
  "Alloy wheels",
  "Ambient lighting",
  "Android Auto",
  "Apple CarPlay",
  "Auto-dimming rear-view mirror",
  "Automatic climate control",
  "Automatic emergency braking",
  "Automatic headlights",
  "Blind spot monitoring",
  "Bluetooth interface",
  "Central locking",
  "Cruise control",
  "DAB radio",
  "Digital cockpit",
  "Driver attention assistant",
  "Electric folding mirrors",
  "Electric tailgate",
  "Electronic stability program",
  "Front parking sensors",
  "Heated front seats",
  "Hill-start assist",
  "Isofix child seat mounts",
  "Keyless entry",
  "Lane keeping assistant",
  "LED daytime running lights",
  "LED headlights",
  "Light and rain sensor",
  "Media display",
  "Multifunction steering wheel",
  "Navigation system",
  "On-board computer",
  "Panoramic glass roof",
  "Parking assistant",
  "Passenger airbag deactivation",
  "Rear parking sensors",
  "Rear privacy glass",
  "Reversing camera",
  "Roof rails",
  "Seat heating rear",
  "Speed limiter",
  "Split-folding rear seats",
  "Traction control",
  "Traffic sign recognition",
  "Tyre pressure monitoring",
  "USB-C ports",
  "Voice control",
  "Winter wheels",
];

export const optionalEquipmentCatalog = [
  "Acceleration Boost",
  "Adaptive air suspension",
  "Advanced parking package",
  "Black exterior package",
  "Ceramic brakes",
  "Cold weather package",
  "Comfort access",
  "Enhanced Autopilot",
  "Factory tow bar",
  "Full self-driving capability",
  "Head-up display",
  "Heat pump",
  "Leather upholstery",
  "Matrix LED headlights",
  "Metallic paint",
  "Night package",
  "Performance package",
  "Premium audio system",
  "Quickclear heated windscreen",
  "Rear entertainment system",
  "S line package",
  "Sport chrono package",
  "Sport seats",
  "Sunroof",
  "Technology package",
  "Third-row seats",
  "Tow hitch preparation",
  "Ventilated seats",
  "Wireless phone charging",
  "Winter package",
];

export const retrofitCatalog = [
  "Anti-theft device",
  "Ceramic paint protection",
  "Dashcam",
  "Detachable tow bar",
  "Fixed tow bar",
  "Portable navigation system",
  "Roof box carrier",
  "Stationary heating",
  "Swiss motorway vignette holder",
  "Wheel storage bags",
];
